// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66HwrO6ok1UbvcszN9RCWlg0elhUMAFU',
    appId: '1:333389203809:web:fa0845877cef1328551d20',
    messagingSenderId: '333389203809',
    projectId: 'ivory-folder-457413-b3',
    authDomain: 'ivory-folder-457413-b3.firebaseapp.com',
    storageBucket: 'ivory-folder-457413-b3.firebasestorage.app',
    measurementId: 'G-FRJKRJP1T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMxm2mUKUE12SB6HHVRUGV-n1jR5kExU',
    appId: '1:333389203809:android:e550f5964c5faa5d551d20',
    messagingSenderId: '333389203809',
    projectId: 'ivory-folder-457413-b3',
    storageBucket: 'ivory-folder-457413-b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjESuiFfI3aOA8anI2YJy_YicH2vMItbU',
    appId: '1:333389203809:ios:8d338759ff0131b5551d20',
    messagingSenderId: '333389203809',
    projectId: 'ivory-folder-457413-b3',
    storageBucket: 'ivory-folder-457413-b3.firebasestorage.app',
    iosBundleId: 'com.example.souqak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjESuiFfI3aOA8anI2YJy_YicH2vMItbU',
    appId: '1:333389203809:ios:8d338759ff0131b5551d20',
    messagingSenderId: '333389203809',
    projectId: 'ivory-folder-457413-b3',
    storageBucket: 'ivory-folder-457413-b3.firebasestorage.app',
    iosBundleId: 'com.example.souqak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC66HwrO6ok1UbvcszN9RCWlg0elhUMAFU',
    appId: '1:333389203809:web:e6d4ba1557290c34551d20',
    messagingSenderId: '333389203809',
    projectId: 'ivory-folder-457413-b3',
    authDomain: 'ivory-folder-457413-b3.firebaseapp.com',
    storageBucket: 'ivory-folder-457413-b3.firebasestorage.app',
    measurementId: 'G-W5RXMLMHFW',
  );
}
